name: flunar_capital
description: "Gensokyo Radio Player berbasis Flutter"
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  radio_player: ^1.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
